version: '3.7'
services:
    postgres:
        image: postgres:10.5
        container_name: postgres-pszemoapp
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5440:5432'
        volumes:
          - ./docker/postgres-data:/var/lib/postgresql/data
          - ./models/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:

